output "resource_group_name" {
  description = "Resource Group used by AKS"
  value       = data.azurerm_resource_group.rg.name
}

output "aks_cluster_name" {
  description = "AKS cluster name"
  value       = azurerm_kubernetes_cluster.aks.name
}

output "aks_fqdn" {
  description = "AKS API server FQDN"
  value       = azurerm_kubernetes_cluster.aks.fqdn
}

output "vnet_name" {
  description = "Virtual network name used by AKS"
  value       = azurerm_virtual_network.aks.name
}

output "aks_subnet_id" {
  description = "Subnet ID attached to the AKS default node pool"
  value       = azurerm_subnet.aks_nodes.id
}

output "private_cluster_enabled" {
  description = "Whether AKS private cluster is enabled"
  value       = azurerm_kubernetes_cluster.aks.private_cluster_enabled
}

output "log_analytics_workspace_id" {
  description = "Log Analytics Workspace ID used by AKS monitoring"
  value       = try(azurerm_log_analytics_workspace.aks[0].id, null)
}

output "kube_config_raw" {
  description = "Raw kubeconfig generated by AKS"
  value       = azurerm_kubernetes_cluster.aks.kube_config_raw
  sensitive   = true
}

output "kube_config_data_base64" {
  description = "Base64-encoded kubeconfig for GitHub secret KUBE_CONFIG_DATA"
  value       = base64encode(azurerm_kubernetes_cluster.aks.kube_config_raw)
  sensitive   = true
}
