name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: pipeline-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit_test:
    uses: ./.github/workflows/_unit_test.yml
    secrets: inherit

  main_build:
    needs: unit_test
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/_build.yml
    secrets: inherit

  main_deploy:
    needs: main_build
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/_deploy.yml
    with:
      image_tag: ${{ needs.main_build.outputs.image_tag }}
    secrets: inherit

  k6:
    needs: main_deploy
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/_k6.yml
    secrets: inherit